"""adiciona saldo inicial e configuracao inicial

Revision ID: 220f55d9831b
Revises: 29469f65c9c7
Create Date: 2026-05-03 19:36:25.211982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220f55d9831b'
down_revision: Union[str, Sequence[str], None] = '29469f65c9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('configuracao_inicial_concluida', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'configuracao_inicial_concluida')
    # ### end Alembic commands ###
