"""adiciona saldo inicial ao usuario

Revision ID: 29469f65c9c7
Revises: cd508ad835ea
Create Date: 2026-05-03 19:03:48.649721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29469f65c9c7'
down_revision: Union[str, Sequence[str], None] = 'cd508ad835ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('saldo_inicial', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'saldo_inicial')
    # ### end Alembic commands ###
