"""adiciona renda mensal ao usuario

Revision ID: 89d0d6ffff46
Revises: c95425902f5a
Create Date: 2026-05-03 18:38:16.813309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d0d6ffff46'
down_revision: Union[str, Sequence[str], None] = 'c95425902f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('renda_mensal', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'renda_mensal')
    # ### end Alembic commands ###
