"""adiciona renda mensal ao usuario

Revision ID: cd508ad835ea
Revises: 89d0d6ffff46
Create Date: 2026-05-03 18:43:46.149666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd508ad835ea'
down_revision: Union[str, Sequence[str], None] = '89d0d6ffff46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
